name: dairy_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 # 日付フォーマットのためのパッケージ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
